# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec

# 2. Installed Plugin
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-twitter-plugin

# 3. Gem settings
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: Chaotikum_ev # jekyll-seo-tag > Owners twitter username
author: Chaotikum e.V. # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Chaotikum e.V. # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/chaotikum_ev
    - https://github.com/Chaotikum

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
paginate: 10
excerpt_separator: <!--more-->
timezone: Europe/Berlin # Timezone for blog posts and alike
baseurl: /chaotikum

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    feature_image: "/assets/logo.jpg"
  projects:
    title: Projekte # Needed for Siteleaf
    output: true
    feature_image: "/assets/projekte.jpg"
    permalink: project/:path/
  press:
    output: false

# 6. Jekyll collections settings
defaults:
  -
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: de # Set the site language
title: "Chaotikum.org" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.png" # Site logo, also used in jekyll-seo-tag
description: "Willkommen beim Chaotikum e.V., wir beschäftigen uns kreativ mit Technik und ihrer Auswirkungen auf die Gesellschaft und engagieren uns eigenverantwortlich und auf unterschiedliche Weise für Informations- und Kommunikationsfreiheit."
url: "http://fritz.nobreakspace.org"
#url: "https://chaotikum.org" # Site url, also used in jekyll-seo-tag
email: "info@chaotikum.org"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
twitter_username: Chaotikum_eV

nav_header:
  - title: Home
    subfolder:
      - page: Home
        url: /
  - title: Blog
    subfolder:
      - page: Blog
        url: /blog/
      - page: Presse
        url: /press/
  - title: Projekte
    subfolder:
      - page: Projekte
        url: /projects/
  - title: Verein
    subfolder:
      - page: Verein
        url: /verein/
      - page: Hackerspace
        url: /nobreakspace/
      - page: Leitbild
        url: /leitbild/
  - title: Veranstaltungen
    subfolder:
      - page: Veranstaltungen
        url: /events/
  - title: Suche
    subfolder:
      - page: Suche
        url: /search/
  - title: Wiki
    subfolder:
      - page: Wiki
        url: http://chaotikum.org/start

# 8. Site navigation
navigation_header:
  Blog: /blog/
  Verein: /verein/
  Hackerspace: /nobreakspace/
  Projekte: /projects/
  Veranstaltungen: /events/
  Wiki: http://chaotikum.org/start

navigation_footer:
  Impressum: /impressum/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/chaotikum_ev
  GitHub: https://github.com/Chaotikum
  link: https://chaotikum.org
  RSS: /feed.xml
  Email: "mailto:info@chaotikum.org"

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#1DA1F2"
  facebook: "#3B5998"
  # Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  tumblr: "#36465D"
  Reddit: "#FF4500"
  Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  Email: ""

#Defining reusable html templates for the webste that are places in the _includes folder
image: "image.html"
pressespiegel: "pressespiegel.html"
default-feature: "/assets/logo.jpg"

wikiimage: "https://chaotikum.org/_media"
ccbync: "<a href='https://creativecommons.org/licenses/by-nc/4.0/de/'>CC BY NC</a>"
ccbysa: "<a href='https://creativecommons.org/licenses/by-sa/3.0/de/'>CC BY SA</a>"

vorsitz1: Lukas Ruge
vorsitz2: Johannes Thorn
finanzen: Matthias Schiffer
kontakt: Matthias Schiffer
